name: Bug report
description: Create a report to help us improve
title: ''
labels: ''
assignees: ''

body:
  - type: markdown
    attributes:
      value: |
        **Describe the bug**
        A clear and concise description of what the bug is.

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error

  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.

  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.

  - type: input
    attributes:
      label: WordPress version
      description: The version of WordPress you are using.

  - type: input
    attributes:
      label: PHP version
      description: The version of PHP you are using.

  - type: input
    attributes:
      label: Desktop (please complete the following information)
      description: |
        - OS: [e.g. iOS]
        - Browser [e.g. chrome, safari]
        - Version [e.g. 22]

  - type: input
    attributes:
      label: Smartphone (please complete the following information)
      description: |
        - Device: [e.g. iPhone6]
        - OS: [e.g. iOS8.1]
        - Browser [e.g. stock browser, safari]
        - Version [e.g. 22]

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.