name: Feature request
description: Suggest an idea for this project

body:
  - type: textarea
    attributes:
      label: Feature description
      description: A clear and concise description of the feature you are requesting.

  - type: textarea
    attributes:
      label: Problem to solve
      description: Describe the problem this feature will solve.

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.